### ISSUE TITLE
Simple diagonal win not recognized

### ISSUE THREAD

**Issue by dekonvoluted** [sadanand-singh/TicTacToe#1]
Steps to replicate:
1. python main.py
2. Click along a diagonal from the top left to the bottom right.
3. Not only does the code not block this win path, but it doesn't recognize that the game is over. This lets me win "twice-over" as seen in these examples: 
   ![Example 1](http://i.imgur.com/sQ4OteR.png)
   ![Example 2](http://i.imgur.com/w4q7HHj.png)

**Comment by sadanand-singh** [comment]
Fixed now. The end check login was flawed before. It was working on my Mac, but not on the Arch Machine. I will look into it later why was that happening. Currently things are working too perfectly.:)
